name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Source Code
          uses: actions/checkout@v3
        - name: make
          run: "cd src; make"
        - name: test
          run: "cd src; ./kerf_test"
